version: '3.8'
services:
  db:
    container_name: 'app_db'
    image: postgres:16
    env_file:
      - app/.env.prod
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  hik_app:
    container_name: "app"
    build:
      context: .
    depends_on:
      - db
    env_file:
      - app/.env.prod
    ports:
      - "9900:8000"
    restart: always