"""Changing unique politic

Revision ID: 33752c1061a8
Revises: 6ffb69cd10c8
Create Date: 2024-05-25 16:54:46.078090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33752c1061a8'
down_revision: Union[str, None] = '6ffb69cd10c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('records_record_id_key', 'records', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('records_record_id_key', 'records', ['record_id'])
    # ### end Alembic commands ###
