"""Added to records model Object_id

Revision ID: 3c5e43f5e522
Revises: 0c7c75e55938
Create Date: 2024-05-26 16:39:06.230703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5e43f5e522'
down_revision: Union[str, None] = '0c7c75e55938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('object_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'object_id')
    # ### end Alembic commands ###
