"""Changing logical net

Revision ID: 7c5d321de471
Revises: 82fa90e256fb
Create Date: 2024-05-20 14:58:04.939217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5d321de471'
down_revision: Union[str, None] = '82fa90e256fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_areas_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'area_id')
    )
    op.drop_table('user_group_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='user_group_association_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], name='user_group_association_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name='user_group_association_pkey')
    )
    op.drop_table('user_areas_association')
    # ### end Alembic commands ###
