"""Return unique to Records

Revision ID: 87c24331ff5f
Revises: 6ffb69cd10c8
Create Date: 2024-05-25 23:40:10.317800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c24331ff5f'
down_revision: Union[str, None] = '6ffb69cd10c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
