"""Second creation

Revision ID: ca1bec135ee4
Revises: bed2a7279f6e
Create Date: 2024-05-12 23:50:52.252413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1bec135ee4'
down_revision: Union[str, None] = 'bed2a7279f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('own_id', sa.String(), nullable=False))
    op.drop_column('areas', 'area_own_id')
    op.add_column('devices', sa.Column('own_id', sa.String(), nullable=False))
    op.drop_column('devices', 'device_own_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_own_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('devices', 'own_id')
    op.add_column('areas', sa.Column('area_own_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('areas', 'own_id')
    # ### end Alembic commands ###
